version: "3"

services:
  web:
    build: .
    command: nodemon -L
    volumes:
      - ./backend:/code
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: mongo:3.0.15-wheezy
    volumes:
      - db-data:/var/db/data

volumes:
  db-data